name: Python Formatting (run `black .` to fix)

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@22.12.0
        with:
          version: 22.12.0
