name: Compile and Deploy

on:
  push:
    branches:
      - main

jobs:

  get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Versions
        id: versions
        run: |
          versions=( $(git branch -r --list "origin/v*[0-9\.]" | cut -d "/" -f 2))
          quoted=()
          for line in "${versions[@]}"; do
            quoted+=("\"$line\"")
          done
          str=$( IFS=$','; echo "${quoted[*]}" )
          echo "versions=[\"main\",$str]" >> $GITHUB_OUTPUT

  compile:
    runs-on: ubuntu-latest
    needs: get-versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.version }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dev Dependencies
        run: |
          sudo apt-get install gettext

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process translations
        run: |
          ./bw-dev messages:update

      - name: Compile site
        run: |
          python generate.py ${{ matrix.version }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: BookWyrm Bot
          commit_message: deploy versions
          commit_author: BookWyrm Bot <joinbookwyrm@users.noreply>

      - name: Deploy latest to server
        if:  ${{ matrix.version == 'main' }}
        id: deploy-versions
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete --exclude="v*[0-9\.]/**"'
          options: ''
          ssh_options: ''
          src: 'site/'
          dest: 'mouse@docs.joinbookwyrm.com:/var/www/docs-bookwyrm/html'

      - name: Deploy versions to server
        if:  ${{ matrix.version != 'main' }}
        id: deploy-versions
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'site/'
          dest: 'mouse@docs.joinbookwyrm.com:/var/www/docs-bookwyrm/html/${{ matrix.version }}'